import unreal

BL_Mapping=unreal.AssetToolsHelpers.get_asset_tools().create_asset('BL_Mapping','/Engine/Functions/BLUI/', unreal.MaterialFunction, unreal.MaterialFunctionFactoryNew())

create_expression = unreal.MaterialEditingLibrary.create_material_expression_in_function
create_connection = unreal.MaterialEditingLibrary.connect_material_expressions
connect_property = unreal.MaterialEditingLibrary.connect_material_property
update_function = unreal.MaterialEditingLibrary.update_material_function

mat_func_separate = unreal.load_asset('/Engine/Functions/Engine_MaterialFunctions02/Utility/BreakOutFloat3Components')
mat_func_combine = unreal.load_asset('/Engine/Functions/Engine_MaterialFunctions02/Utility/MakeFloat3')

### Creating Nodes
CombineXYZ02 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,580.0, 2880.0)
SeparateXYZ03 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,-740.0, 3180.0)
Math06 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-580.0, 3000.0)
Math05 = create_expression(BL_Mapping,unreal.MaterialExpressionDivide,-380.0, 3000.0)
Cosine03 = create_expression(BL_Mapping,unreal.MaterialExpressionCosine,-80.0, 2680.0)
Cosine02 = create_expression(BL_Mapping,unreal.MaterialExpressionCosine,-100.0, 3220.0)
Subtract01 = create_expression(BL_Mapping,unreal.MaterialExpressionSubtract,360.0, 2720.0)
Multiply201 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,160.0, 2820.0)
Multiply101 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,160.0, 2660.0)
Multiply301 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,160.0, 3040.0)
Multiply401 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,180.0, 3220.0)
Add01 = create_expression(BL_Mapping,unreal.MaterialExpressionAdd,360.0, 3060.0)
CombineXYZ01 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,-1020.0, 2960.0)
Math04 = create_expression(BL_Mapping,unreal.MaterialExpressionDivide,-2000.0, 3000.0)
Math03 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-2160.0, 3000.0)
SeparateXYZ02 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,-2340.0, 3160.0)
Cosine01 = create_expression(BL_Mapping,unreal.MaterialExpressionCosine,-1680.0, 2720.0)
Sine = create_expression(BL_Mapping,unreal.MaterialExpressionSine,-1680.0, 2880.0)
Cosine = create_expression(BL_Mapping,unreal.MaterialExpressionCosine,-1700.0, 3220.0)
Sine01 = create_expression(BL_Mapping,unreal.MaterialExpressionSine,-1680.0, 3040.0)
Subtract = create_expression(BL_Mapping,unreal.MaterialExpressionSubtract,-1260.0, 2740.0)
Multiply2 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-1480.0, 2840.0)
Multiply1 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-1480.0, 2680.0)
Multiply3 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-1460.0, 3020.0)
Multiply4 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-1420.0, 3200.0)
Add = create_expression(BL_Mapping,unreal.MaterialExpressionAdd,-1260.0, 3040.0)
CombineXYZ = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,-2640.0, 3000.0)
CombineXYZ03 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,2140.0, 2880.0)
SeparateXYZ04 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,840.0, 3120.0)
Cosine05 = create_expression(BL_Mapping,unreal.MaterialExpressionCosine,1500.0, 3240.0)
Sine05 = create_expression(BL_Mapping,unreal.MaterialExpressionSine,1500.0, 3040.0)
Multiply302 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,1720.0, 3040.0)
Multiply402 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,1740.0, 3220.0)
Add02 = create_expression(BL_Mapping,unreal.MaterialExpressionAdd,1900.0, 3040.0)
Cosine04 = create_expression(BL_Mapping,unreal.MaterialExpressionCosine,1480.0, 2660.0)
Sine04 = create_expression(BL_Mapping,unreal.MaterialExpressionSine,1500.0, 2880.0)
Subtract02 = create_expression(BL_Mapping,unreal.MaterialExpressionSubtract,1900.0, 2720.0)
Multiply202 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,1700.0, 2820.0)
Multiply102 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,1700.0, 2660.0)
Math08 = create_expression(BL_Mapping,unreal.MaterialExpressionDivide,1220.0, 2960.0)
Math07 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,1040.0, 2960.0)
Math10 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,2820.0, 2980.0)
Math09 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,2820.0, 2820.0)
Math02 = create_expression(BL_Mapping,unreal.MaterialExpressionSubtract,-2900.0, 3140.0)
Math01 = create_expression(BL_Mapping,unreal.MaterialExpressionSubtract,-2900.0, 2960.0)
Math = create_expression(BL_Mapping,unreal.MaterialExpressionSubtract,-2900.0, 2800.0)
SeparateXYZ05 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,2460.0, 3100.0)
Math11 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,2820.0, 3140.0)
CombineXYZ04 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,3100.0, 2980.0)
Sine03 = create_expression(BL_Mapping,unreal.MaterialExpressionSine,-100.0, 2900.0)
Sine02 = create_expression(BL_Mapping,unreal.MaterialExpressionSine,-100.0, 3040.0)
SeparateXYZ06 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,-3320.0, 2900.0)
SeparateXYZ01 = create_expression(BL_Mapping, unreal.MaterialExpressionMaterialFunctionCall, -3320.0, 2780.0)
SeparateXYZ07 = create_expression(BL_Mapping,unreal.MaterialExpressionMaterialFunctionCall,-2340.0, 3000.0)
Angle_Divide = create_expression(BL_Mapping,unreal.MaterialExpressionConstant,-2640.0, 3140.0)
Angle_Multiply = create_expression(BL_Mapping,unreal.MaterialExpressionConstant,-2640.0, 3240.0)
Angle_Y_Invert = create_expression(BL_Mapping,unreal.MaterialExpressionConstant,-2640.0, 3320.0)
Math12 = create_expression(BL_Mapping,unreal.MaterialExpressionMultiply,-2340.0, 3300.0)
SeparateXYZ08 = create_expression(BL_Mapping, unreal.MaterialExpressionMaterialFunctionCall, 2460.0, 2960.0)

OutputResult = create_expression(BL_Mapping,unreal.MaterialExpressionFunctionOutput,3300.0, 2980.0)
VectorInput = create_expression(BL_Mapping, unreal.MaterialExpressionFunctionInput, -3560.0, 2700.0)
VectorInput.input_name = 'VectorInput'
Location = create_expression(BL_Mapping, unreal.MaterialExpressionFunctionInput, -3560.0, 2880.0)
Location.input_name = 'Location'
Rotation = create_expression(BL_Mapping, unreal.MaterialExpressionFunctionInput, -2640.0, 2800.0)
Rotation.input_name = 'Rotation'
Scale = create_expression(BL_Mapping, unreal.MaterialExpressionFunctionInput, 2140.0, 2680.0)
Scale.input_name = 'Scale'

### Loading Material Functions and Textures
CombineXYZ02.set_editor_property('material_function',mat_func_combine)
SeparateXYZ03.set_editor_property('material_function',mat_func_separate)
CombineXYZ01.set_editor_property('material_function',mat_func_combine)
SeparateXYZ02.set_editor_property('material_function',mat_func_separate)
CombineXYZ.set_editor_property('material_function',mat_func_combine)
CombineXYZ03.set_editor_property('material_function',mat_func_combine)
SeparateXYZ04.set_editor_property('material_function',mat_func_separate)
SeparateXYZ05.set_editor_property('material_function',mat_func_separate)
CombineXYZ04.set_editor_property('material_function',mat_func_combine)
SeparateXYZ06.set_editor_property('material_function',mat_func_separate)
SeparateXYZ01.set_editor_property('material_function',mat_func_separate)
SeparateXYZ07.set_editor_property('material_function',mat_func_separate)
SeparateXYZ08.set_editor_property('material_function',mat_func_separate)

### Setting Values
Angle_Divide.r = 180.0
Angle_Multiply.r = 3.1419999599456787
Angle_Y_Invert.r = -1.0

### Creating Connections
CombineXYZ02_connection = create_connection(CombineXYZ02, 'Result', SeparateXYZ04, 'Float3')
SeparateXYZ03_connection = create_connection(SeparateXYZ03, 'R', Multiply101, 'B')
SeparateXYZ03_connection = create_connection(SeparateXYZ03, 'R', Multiply301, 'B')
SeparateXYZ03_connection = create_connection(SeparateXYZ03, 'G', CombineXYZ02, 'Y')
SeparateXYZ03_connection = create_connection(SeparateXYZ03, 'B', Multiply201, 'B')
SeparateXYZ03_connection = create_connection(SeparateXYZ03, 'B', Multiply401, 'B')
Math06_connection = create_connection(Math06, '', Math05, 'A')
Math05_connection = create_connection(Math05, '', Sine03, '')
Math05_connection = create_connection(Math05, '', Cosine02, '')
Math05_connection = create_connection(Math05, '', Sine02, '')
Math05_connection = create_connection(Math05, '', Cosine03, '')
Cosine03_connection = create_connection(Cosine03, '', Multiply101, 'A')
Cosine02_connection = create_connection(Cosine02, '', Multiply401, 'A')
Subtract01_connection = create_connection(Subtract01, '', CombineXYZ02, 'X')
Multiply201_connection = create_connection(Multiply201, '', Subtract01, 'B')
Multiply101_connection = create_connection(Multiply101, '', Subtract01, 'A')
Multiply301_connection = create_connection(Multiply301, '', Add01, 'A')
Multiply401_connection = create_connection(Multiply401, '', Add01, 'B')
Add01_connection = create_connection(Add01, '', CombineXYZ02, 'Z')
CombineXYZ01_connection = create_connection(CombineXYZ01, 'Result', SeparateXYZ03, 'Float3')
Math04_connection = create_connection(Math04, '', Sine, '')
Math04_connection = create_connection(Math04, '', Cosine, '')
Math04_connection = create_connection(Math04, '', Sine01, '')
Math04_connection = create_connection(Math04, '', Cosine01, '')
Math03_connection = create_connection(Math03, '', Math04, 'A')
SeparateXYZ02_connection = create_connection(SeparateXYZ02, 'R', CombineXYZ01, 'X')
SeparateXYZ02_connection = create_connection(SeparateXYZ02, 'G', Multiply1, 'B')
SeparateXYZ02_connection = create_connection(SeparateXYZ02, 'G', Multiply3, 'B')
SeparateXYZ02_connection = create_connection(SeparateXYZ02, 'B', Multiply2, 'B')
SeparateXYZ02_connection = create_connection(SeparateXYZ02, 'B', Multiply4, 'B')
Cosine01_connection = create_connection(Cosine01, '', Multiply1, 'A')
Sine_connection = create_connection(Sine, '', Multiply2, 'A')
Cosine_connection = create_connection(Cosine, '', Multiply4, 'A')
Sine01_connection = create_connection(Sine01, '', Multiply3, 'A')
Subtract_connection = create_connection(Subtract, '', CombineXYZ01, 'Y')
Multiply2_connection = create_connection(Multiply2, '', Subtract, 'B')
Multiply1_connection = create_connection(Multiply1, '', Subtract, 'A')
Multiply3_connection = create_connection(Multiply3, '', Add, 'A')
Multiply4_connection = create_connection(Multiply4, '', Add, 'B')
Add_connection = create_connection(Add, '', CombineXYZ01, 'Z')
CombineXYZ_connection = create_connection(CombineXYZ, 'Result', SeparateXYZ02, 'Float3')
CombineXYZ03_connection = create_connection(CombineXYZ03, 'Result', SeparateXYZ05, 'Float3')
SeparateXYZ04_connection = create_connection(SeparateXYZ04, 'R', Multiply102, 'B')
SeparateXYZ04_connection = create_connection(SeparateXYZ04, 'R', Multiply302, 'B')
SeparateXYZ04_connection = create_connection(SeparateXYZ04, 'G', Multiply202, 'B')
SeparateXYZ04_connection = create_connection(SeparateXYZ04, 'G', Multiply402, 'B')
SeparateXYZ04_connection = create_connection(SeparateXYZ04, 'B', CombineXYZ03, 'Z')
Cosine05_connection = create_connection(Cosine05, '', Multiply402, 'A')
Sine05_connection = create_connection(Sine05, '', Multiply302, 'A')
Multiply302_connection = create_connection(Multiply302, '', Add02, 'A')
Multiply402_connection = create_connection(Multiply402, '', Add02, 'B')
Add02_connection = create_connection(Add02, '', CombineXYZ03, 'Y')
Cosine04_connection = create_connection(Cosine04, '', Multiply102, 'A')
Sine04_connection = create_connection(Sine04, '', Multiply202, 'A')
Subtract02_connection = create_connection(Subtract02, '', CombineXYZ03, 'X')
Multiply202_connection = create_connection(Multiply202, '', Subtract02, 'B')
Multiply102_connection = create_connection(Multiply102, '', Subtract02, 'A')
Math08_connection = create_connection(Math08, '', Sine04, '')
Math08_connection = create_connection(Math08, '', Cosine05, '')
Math08_connection = create_connection(Math08, '', Sine05, '')
Math08_connection = create_connection(Math08, '', Cosine04, '')
Math07_connection = create_connection(Math07, '', Math08, 'A')
Math10_connection = create_connection(Math10, '', CombineXYZ04, 'Y')
Math09_connection = create_connection(Math09, '', CombineXYZ04, 'X')
Math02_connection = create_connection(Math02, '', CombineXYZ, 'Z')
Math01_connection = create_connection(Math01, '', CombineXYZ, 'Y')
Math_connection = create_connection(Math, '', CombineXYZ, 'X')
SeparateXYZ05_connection = create_connection(SeparateXYZ05, 'R', Math09, 'B')
SeparateXYZ05_connection = create_connection(SeparateXYZ05, 'G', Math10, 'B')
SeparateXYZ05_connection = create_connection(SeparateXYZ05, 'B', Math11, 'B')
Math11_connection = create_connection(Math11, '', CombineXYZ04, 'Z')
Sine03_connection = create_connection(Sine03, '', Multiply201, 'A')
Sine02_connection = create_connection(Sine02, '', Multiply301, 'A')
SeparateXYZ06_connection = create_connection(SeparateXYZ06, 'R', Math, 'B')
SeparateXYZ06_connection = create_connection(SeparateXYZ06, 'G', Math01, 'B')
SeparateXYZ06_connection = create_connection(SeparateXYZ06, 'B', Math02, 'B')
SeparateXYZ01_connection = create_connection(SeparateXYZ01, 'R', Math, 'A')
SeparateXYZ01_connection = create_connection(SeparateXYZ01, 'G', Math01, 'A')
SeparateXYZ01_connection = create_connection(SeparateXYZ01, 'B', Math02, 'A')
Location_connection = create_connection(Location, '', SeparateXYZ06, 'Float3')
VectorInput_connection = create_connection(VectorInput, '', SeparateXYZ01, 'Float3')
Rotation_connection = create_connection(Rotation, '', SeparateXYZ07, 'Float3')
SeparateXYZ07_connection = create_connection(SeparateXYZ07, 'R', Math03, 'A')
SeparateXYZ07_connection = create_connection(SeparateXYZ07, 'G', Math06, 'A')
SeparateXYZ07_connection = create_connection(SeparateXYZ07, 'B', Math07, 'A')
Angle_Divide_connection = create_connection(Angle_Divide, '', Math04, 'B')
Angle_Divide_connection = create_connection(Angle_Divide, '', Math05, 'B')
Angle_Divide_connection = create_connection(Angle_Divide, '', Math08, 'B')
Angle_Multiply_connection = create_connection(Angle_Multiply, '', Math03, 'B')
Angle_Multiply_connection = create_connection(Angle_Multiply, '', Math07, 'B')
Angle_Multiply_connection = create_connection(Angle_Multiply, '', Math12, 'A')
Angle_Y_Invert_connection = create_connection(Angle_Y_Invert, '', Math12, 'B')
Math12_connection = create_connection(Math12, '', Math06, 'B')
Scale_connection = create_connection(Scale, '', SeparateXYZ08, 'Float3')
SeparateXYZ08_connection = create_connection(SeparateXYZ08, 'R', Math09, 'A')
SeparateXYZ08_connection = create_connection(SeparateXYZ08, 'G', Math10, 'A')
SeparateXYZ08_connection = create_connection(SeparateXYZ08, 'B', Math11, 'A')
CombineXYZ04_connection = create_connection(CombineXYZ04, 'Result', OutputResult, '')

update_function()